<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:dc="http://purl.org/dc/elements/1.1/"  xmlns:isc="http://dtd.3dcart.com/ecommerce-1.0.dtd">
<channel>
<title><![CDATA[Sample Store: ]]></title>
<link>https://wanderland-preview-com.3dcartstores.com</link>
<pubDate>Mon, 14 Sep 2020 00:00:00 EST</pubDate>
<description><![CDATA[ at Sample Store]]></description>
<language>en-us</language>
<isc:store_name><![CDATA[Sample Store]]></isc:store_name>
<item>
<title><![CDATA[Tangram Puzzle]]></title>
<link>https://wanderland-preview-com.3dcartstores.com/Tangram-Puzzle_p_9.html</link>
<pubDate>Mon, 14 Sep 2020 00:00:00 EST</pubDate>
<description><![CDATA[ <p><a href="https://wanderland-preview-com.3dcartstores.com/Tangram-Puzzle_p_9.html?referrer=rss"><img src="https://wanderland-preview-com.3dcartstores.com/assets/images/thumbnails/product3_thumbnail.jpg" align="right" border=0></a>Anvil has given this adorable tee the softness to make you want to wear it again and again.Pre-shrunk 100% combed ring-spun cotton3.2-oz.Classic contoured silhouette with side seamsDisplay tape and single-needle seamed mitered v-neckDouble-needle sle...<a href="https://wanderland-preview-com.3dcartstores.com/Tangram-Puzzle_p_9.html?referrer=rss">[Read More]</a><br><b>Our Price:</b> $16.99 <font color="red">On Sale</font> [<a href="https://wanderland-preview-com.3dcartstores.com/add_cart.asp?quick=1&item_id=9&out=1" target="_new">Add to Cart</a>]</p><br clear=all> ]]></description>
<guid isPermaLink="false">https://wanderland-preview-com.3dcartstores.com/Tangram-Puzzle_p_9.html</guid>
<content:encoded><![CDATA[<p><a href="https://wanderland-preview-com.3dcartstores.com/Tangram-Puzzle_p_9.html?referrer=rss"><img src="https://wanderland-preview-com.3dcartstores.com/assets/images/thumbnails/product3_thumbnail.jpg" align="right" border=0></a>Anvil has given this adorable tee the softness to make you want to wear it again and again.Pre-shrunk 100% combed ring-spun cotton3.2-oz.Classic contoured silhouette with side seamsDisplay tape and single-needle seamed mitered v-neckDouble-needle sle...<a href="https://wanderland-preview-com.3dcartstores.com/Tangram-Puzzle_p_9.html?referrer=rss">[Read More]</a><br><b>Our Price:</b> $16.99 <font color="red">On Sale</font> [<a href="https://wanderland-preview-com.3dcartstores.com/add_cart.asp?quick=1&item_id=9&out=1" target="_new">Add to Cart</a>]</p><br clear=all>]]></content:encoded>
<isc:description><![CDATA[<div>Anvil has given this adorable tee the softness to make you want to wear it again and again.</div><div><br></div><div>Pre-shrunk 100% combed ring-spun cotton</div><div>3.2-oz.</div><div>Classic contoured silhouette with side seams</div><div>Display tape and single-needle seamed mitered v-neck</div><div>Double-needle sleeves and bottom hem</div><div>TearAway label</div><div>Fabric Blend: 100% Cotton</div><div>Neck: V-Neck</div><div>Sleeve: Short sleeve</div><div>Solid/Multi Color: Solid</div><div>Special Features: Fashion</div><div>Special Features: Tearaway Labels</div><div>Special Features: Ring-Spun</div><div><br></div><div><br></div><div>" Sold Individually Please note: If there is a color/size/type option, the option closest to the image will be shipped (Or you may receive a random color/size/type).</div><div><br></div> ]]></isc:description>
<isc:productid><![CDATA[Tangram Puzzle]]></isc:productid>
<isc:thumb><![CDATA[https://wanderland-preview-com.3dcartstores.com/assets/images/thumbnails/product3_thumbnail.jpg]]></isc:thumb>
<isc:image><![CDATA[https://wanderland-preview-com.3dcartstores.com/assets/images/product3.jpg]]></isc:image>
<isc:price><![CDATA[$19.99]]></isc:price>
</item>
<item>
<title><![CDATA[Magnetic Numbers]]></title>
<link>https://wanderland-preview-com.3dcartstores.com/Magnetic-Numbers_p_10.html</link>
<pubDate>Mon, 14 Sep 2020 00:00:00 EST</pubDate>
<description><![CDATA[ <p><a href="https://wanderland-preview-com.3dcartstores.com/Magnetic-Numbers_p_10.html?referrer=rss"><img src="https://wanderland-preview-com.3dcartstores.com/assets/images/thumbnails/product4_thumbnail.jpg" align="right" border=0></a>You can't help but feel great in this fashionable ring-spun tee from Anvil.Preshrunk 100% combed ring-spun cotton4.5-oz.Classic contoured silhouette with side seamsShoulder-to-shoulder tapingSeamed collarDouble-needle sleeves and bottom hemTearAway; ...<a href="https://wanderland-preview-com.3dcartstores.com/Magnetic-Numbers_p_10.html?referrer=rss">[Read More]</a><br><b>Our Price:</b> $25.99 <font color="red"></font> [<a href="https://wanderland-preview-com.3dcartstores.com/add_cart.asp?quick=1&item_id=10&out=1" target="_new">Add to Cart</a>]</p><br clear=all> ]]></description>
<guid isPermaLink="false">https://wanderland-preview-com.3dcartstores.com/Magnetic-Numbers_p_10.html</guid>
<content:encoded><![CDATA[<p><a href="https://wanderland-preview-com.3dcartstores.com/Magnetic-Numbers_p_10.html?referrer=rss"><img src="https://wanderland-preview-com.3dcartstores.com/assets/images/thumbnails/product4_thumbnail.jpg" align="right" border=0></a>You can't help but feel great in this fashionable ring-spun tee from Anvil.Preshrunk 100% combed ring-spun cotton4.5-oz.Classic contoured silhouette with side seamsShoulder-to-shoulder tapingSeamed collarDouble-needle sleeves and bottom hemTearAway; ...<a href="https://wanderland-preview-com.3dcartstores.com/Magnetic-Numbers_p_10.html?referrer=rss">[Read More]</a><br><b>Our Price:</b> $25.99 <font color="red"></font> [<a href="https://wanderland-preview-com.3dcartstores.com/add_cart.asp?quick=1&item_id=10&out=1" target="_new">Add to Cart</a>]</p><br clear=all>]]></content:encoded>
<isc:description><![CDATA[<div>You can't help but feel great in this fashionable ring-spun tee from Anvil.</div><div><br></div><div>Preshrunk 100% combed ring-spun cotton</div><div>4.5-oz.</div><div>Classic contoured silhouette with side seams</div><div>Shoulder-to-shoulder taping</div><div>Seamed collar</div><div>Double-needle sleeves and bottom hem</div><div>TearAway; label</div><div>Fabric Blend: 100% Cotton</div><div>Neck: Crew</div><div>Sleeve: Short sleeve</div><div>Solid/Multi Color: Solid</div><div>Special Features: Basic</div><div>Special Features: Tearaway Labels</div><div>Special Features: Ring-Spun</div><div><br></div><div><br></div><div>" Sold Individually Please note: If there is a color/size/type option, the option closest to the image will be shipped (Or you may receive a random color/size/type).</div><div><br></div>  ]]></isc:description>
<isc:productid><![CDATA[Magnetic Numbers]]></isc:productid>
<isc:thumb><![CDATA[https://wanderland-preview-com.3dcartstores.com/assets/images/thumbnails/product4_thumbnail.jpg]]></isc:thumb>
<isc:image><![CDATA[https://wanderland-preview-com.3dcartstores.com/assets/images/product4.jpg]]></isc:image>
<isc:price><![CDATA[$25.99]]></isc:price>
</item>
<item>
<title><![CDATA[Alphabet Blocks]]></title>
<link>https://wanderland-preview-com.3dcartstores.com/Alphabet-Blocks_p_11.html</link>
<pubDate>Mon, 14 Sep 2020 00:00:00 EST</pubDate>
<description><![CDATA[ <p><a href="https://wanderland-preview-com.3dcartstores.com/Alphabet-Blocks_p_11.html?referrer=rss"><img src="https://wanderland-preview-com.3dcartstores.com/assets/images/thumbnails/product5_thumbnail.jpg" align="right" border=0></a>You can't help but look good in this fashionable V-Neck from Anvil.Preshrunk 75% combed ring-spun cotton/25% polyester5-oz.26 singlesClassic contoured silhouette with side seamsShoulder-to-shoulder tapingSeamed and mitered v-neckDouble-needle sleeves...<a href="https://wanderland-preview-com.3dcartstores.com/Alphabet-Blocks_p_11.html?referrer=rss">[Read More]</a><br><b>Our Price:</b> $24.99 <font color="red">On Sale</font> [<a href="https://wanderland-preview-com.3dcartstores.com/add_cart.asp?quick=1&item_id=11&out=1" target="_new">Add to Cart</a>]</p><br clear=all> ]]></description>
<guid isPermaLink="false">https://wanderland-preview-com.3dcartstores.com/Alphabet-Blocks_p_11.html</guid>
<content:encoded><![CDATA[<p><a href="https://wanderland-preview-com.3dcartstores.com/Alphabet-Blocks_p_11.html?referrer=rss"><img src="https://wanderland-preview-com.3dcartstores.com/assets/images/thumbnails/product5_thumbnail.jpg" align="right" border=0></a>You can't help but look good in this fashionable V-Neck from Anvil.Preshrunk 75% combed ring-spun cotton/25% polyester5-oz.26 singlesClassic contoured silhouette with side seamsShoulder-to-shoulder tapingSeamed and mitered v-neckDouble-needle sleeves...<a href="https://wanderland-preview-com.3dcartstores.com/Alphabet-Blocks_p_11.html?referrer=rss">[Read More]</a><br><b>Our Price:</b> $24.99 <font color="red">On Sale</font> [<a href="https://wanderland-preview-com.3dcartstores.com/add_cart.asp?quick=1&item_id=11&out=1" target="_new">Add to Cart</a>]</p><br clear=all>]]></content:encoded>
<isc:description><![CDATA[<div>You can't help but look good in this fashionable V-Neck from Anvil.</div><div><br></div><div>Preshrunk 75% combed ring-spun cotton/25% polyester</div><div>5-oz.</div><div>26 singles</div><div>Classic contoured silhouette with side seams</div><div>Shoulder-to-shoulder taping</div><div>Seamed and mitered v-neck</div><div>Double-needle sleeves and bottom hem</div><div>TearAway</div><div>Fabric Blend: Cotton/Poly Blend</div><div>Neck: V-Neck</div><div>Sleeve: Short sleeve</div><div>Solid/Multi Color: Multi Color</div><div>Special Features: Fashion</div><div>Special Features: Tearaway Labels</div><div>Special Features: Ring-Spun</div><div><br></div><div><br></div><div>" Sold Individually Please note: If there is a color/size/type option, the option closest to the image will be shipped (Or you may receive a random color/size/type).</div><div><br></div>  ]]></isc:description>
<isc:productid><![CDATA[Alphabet Blocks]]></isc:productid>
<isc:thumb><![CDATA[https://wanderland-preview-com.3dcartstores.com/assets/images/thumbnails/product5_thumbnail.jpg]]></isc:thumb>
<isc:image><![CDATA[https://wanderland-preview-com.3dcartstores.com/assets/images/product5.jpg]]></isc:image>
<isc:price><![CDATA[$25.99]]></isc:price>
</item>
</channel></rss>